### ISSUE TITLE
Regression method to calculate factor scores

### ISSUE THREAD

**Issue by kaan0nder** [EducationalTestingService/factor_analyzer#118]
When I check the factor analysis in SPSS, there is a method to calculate factor scores with Regression and other 2 methods (Bartlett and Anderson-Rubin).

When I check the factor_analyzer library, we can calculate factor scores with FactorAnalyzer().fit_transform() method but there is no option to calculate, just write the transform method and get the results. 

Is that possible to calculate factor scores with regression method in factor_analyzer library ?

**Comment by desilinguist** [comment]
The `transform()` method in `FactorAnalyzer` [uses](https://github.com/EducationalTestingService/factor_analyzer/issues/118) `np.linalg.solve()` to solve for the weights. Regression methods are currently not supported.
