### ISSUE TITLE
Remove pre-commit from install dependencies, add it to "dev" extra

### ISSUE THREAD

**Issue by jmahlik** [EducationalTestingService/factor_analyzer#129]
**Did you read the notes?**
Yes

**Describe the bug**
`pre-commit` is currently listed as an install dependency of the project but isn't needed at runtime. It is only needed for development.

Pre-commit brings in some transitive dependencies. Moving it to a "dev" extra would reduce the install load for end users. It has about 9 transitive dependencies, so it'd be awesome to not get them installed.

Developers could install with:

```bash
python -m pip install -e .[dev]
```

I'll submit a PR and update the docs.

**To Reproduce**
Install the package, pre-commit will be installed. 

Here's the transitives that pre-commit is bringing in shown with [`pipdeptree`](https://github.com/tox-dev/pipdeptree).

```
python -m pip install pipdeptree factor-analyzer

pipdeptree -p factor-analyzer

factor-analyzer==0.5.0
├── numpy [required: Any, installed: 1.25.2]
├── pandas [required: Any, installed: 1.5.3]
│   ├── numpy [required: >=1.21.0, installed: 1.25.2]
│   ├── numpy [required: >=1.23.2, installed: 1.25.2]
│   ├── python-dateutil [required: >=2.8.1, installed: 2.8.2]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   └── pytz [required: >=2020.1, installed: 2023.3.post1]
├── pre-commit [required: Any, installed: 3.4.0]
│   ├── cfgv [required: >=2.0.0, installed: 3.4.0]
│   ├── identify [required: >=1.0.0, installed: 2.5.28]
│   ├── nodeenv [required: >=0.11.1, installed: 1.8.0]
│   │   └── setuptools [required: Any, installed: 68.2.1]
│   ├── PyYAML [required: >=5.1, installed: 6.0.1]
│   └── virtualenv [required: >=20.10.0, installed: 20.24.5]
│       ├── distlib [required: >=0.3.7,<1, installed: 0.3.7]
│       ├── filelock [required: >=3.12.2,<4, installed: 3.12.3]
│       └── platformdirs [required: >=3.9.1,<4, installed: 3.10.0]
├── scikit-learn [required: Any, installed: 1.3.0]
│   ├── joblib [required: >=1.1.1, installed: 1.3.2]
│   ├── numpy [required: >=1.17.3, installed: 1.25.2]
│   ├── scipy [required: >=1.5.0, installed: 1.11.2]
│   │   └── numpy [required: >=1.21.6,<1.28.0, installed: 1.25.2]
│   └── threadpoolctl [required: >=2.0.0, installed: 3.2.0]
└── scipy [required: Any, installed: 1.11.2]
    └── numpy [required: >=1.21.6,<1.28.0, installed: 1.25.2]
```

**Expected behavior**
pre-commit is not installed, unless specifying the `[dev]` extra

**Versions (please complete the following information):**
 - OS all
 - Python 3.11
 - Versions for `factor_analyzer` / `numpy` / `scipy` / `pandas` main branch

**Additional context**
Removing the transitives reduces the chance for conflicts in versions, download size and chance of triggering security scanners if one of them has a vuln.

**Comment by desilinguist** [comment]
@jmahlik thank you so much for your contribution! I agree that `pre-commit` is not needed as an install dependency and moving it to a dev dependency makes a lot of sense. I will take a look at your PR in the next few days. Much appreciation for helping pay down our technical debt 🙏!
