### ISSUE TITLE
SciPy sum function is deprecated causing Factor-Analyzer to fail

### ISSUE THREAD

**Issue by GoBlue60s** [EducationalTestingService/factor_analyzer#134]
The latest version of SciPy has deprecated the sum function which Factor_Analyzer seems to use.  I believe that replacing it with NumPy's sum function may work.

**Comment by desilinguist** [comment]
Thanks for reporting the issue @GoBlue60s! I will reproduce and start a fix soon.

**Comment by desilinguist** [comment]
Addressed by #135.

**Comment by desilinguist** [comment]
@GoBlue60s v0.5.1 with the fix has been released. Thanks again for filing the issue!

**Comment by GoBlue60s** [comment]
I installed v0.5.1 via PyCharm and tested it.  I can confirm that it has fixed the issue.  Thank you for your prompt attention to this matter.
