### ISSUE TITLE
accessing rotated factor matrix, factor scores

### ISSUE THREAD

**Issue by sebtac** [EducationalTestingService/factor_analyzer#19]
I am looking for a way to return Rotated Factor Matrix and Factor Scores generated by the model preferably with Regression Method. Is it available in the module?

**Comment by jbiggsets** [comment]
@sebtac, you can now generate factor scores and do a variety of rotations on the loading matrix. Is this issue resolved? Let me know, and sorry for the delayed response.

**Comment by jbiggsets** [comment]
Hi @sebtac, I'm going to close this issue. Please file a new issue if you have further questions. Thanks!
