### ISSUE TITLE
Can you give  the formula to be deduced?

### ISSUE THREAD

**Issue by zhangxiaoda007** [EducationalTestingService/factor_analyzer#22]
Hello, I'm researching your factor analysis module
But，I dont know the fromula what you use，
Is it convenient for you to share the basic derivation process?
I want to know the different between it and Spss。
thank you!

**Comment by jbiggsets** [comment]
Hello @zhangxiaoda007,

If you are using the minimum residual/unweighted least squares approach, `method='minres'` (the default), then the formula to derive the (unrotated) factor loading matrix is fairly straightforward.

(1) **Calculate starting values from SMC**: Assuming `use_smc=True` (the default), we begin by calculating the squared multiple correlations from the original correlation matrix. This is equivalent to the matrix you would get from regressing each variable on all of the other variables, and calculating the R-squared. 

Below is the formula for calculating SMC. Assume that `R` is the correlation matrix from the original data set.

`smc = 1 - 1 / diag(inv(R))`

We then subtract the SMC values from the diagonal of the correlation matrix to get the starting values (`x0`) for our unweighted least squares fitting routine. Again, here is the pseudocode for that calculation:

`x0 = diag(R) - smc`

(2) **Fit model using L-BFGS_B**: Once we have calculated the starting values, we fit the model using the [limited-memory BFGS](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) algorithm.

The objective function for this optimization algorithm is (roughly):

```
def objective(x0, R):

    diag(R) = 1 - x0
    eigen_values, eigen_vectors = eigen(R)

    loadings = dot(eigen_vectors, diag(sqrt(eigen_values)))
    model = dot(loadings, loadings.T)

    residual = (R - model)**2
    error = sum(residual)
    return error
```

We also bound the values within the range `(0.005, 1)` to avoid (ultra-)Haywood cases, so this is a constrained optimization problem.

The maximum likelihood approach is slightly more complicated than the minimum residual/unweighted least squares approach, but it usually produces similar results. 

And, of course, the next step is usually to take the unrotated loading matrix and rotate it. There are various rotation algorithms, so it would take a little bit more time to get into that.

If this is not what you are looking for, can you be a bit more specific? If it is what you are looking for, please let me know that, too, so I can close this issue.

Thanks!

**Comment by zhangxiaoda007** [comment]
Hi,
Thank you very much for your reply, which made my doubts answered.
Best


| |
张绍伟
|
|
zhangsw1991@163.com
|
签名由网易邮箱大师定制
On 1/30/2019 03:12，jbiggsets<notifications@github.com> wrote：

Hello @zhangxiaoda007,

If you are using minimum residual/unweighted least squares approach, method='minres' (the default), then the formula to derive the (unrotated) factor loading matrix is fairly straightforward.

(1) Calculate starting values from SMC: Assuming use_smc=True (the default), we begin by calculating the squared multiple correlations from the original correlation matrix. This is equivalent to the matrix you would get from regressing each variable on all of the other variables, and calculating the R-squared.

Below is the formula for calculating SMC. Assume that R is the correlation matrix from the original data set.

smc = 1 - 1 / diag(inv(R))

We then subtract the SMC values from the diagonal of the correlation matrix to get the starting values (x0) for our unweighted least squares fitting routine. Again, here is the pseudocode for that calculation:

x0 = diag(R) - smc

(2) Fit model using L-BFGS_B: Once we have calculated the starting values, we fit the model using the limited-memory BFGS algorithm.

The objective function for this optimization algorithm is (roughly):

def objective(x0, R):

    diag(R) = 1 - x0
    eigen_values, eigen_vectors = eigen(R)

    loadings = dot(eigen_vectors, diag(sqrt(eigen_values)))
    model = dot(loadings, loadings.T)

    residual = (R - model)**2
    error = sum(residual)
    return error


We also bound the values with the range (0.005, 1) so as to avoid (ultra-)Haywood cases, so this is a constrained optimization problem.

The maximum likelihood approach is slightly more complicated than the minimum residual/unweighted least squares approach, but it usually produces similar results.

And, of course, the next step is usually to take the unrotated loading matrix and rotate it. There are various rotation algorithms, so it would take a little bit more time to get into that.

If this is not what you are looking for, can you be a bit more specific? If it is what you are looking for, please let me know that, too, so I can close this issue.

Thanks!

**Comment by jbiggsets** [comment]
Thanks, @zhangxiaoda007. I am going to close this issue. Please feel free to email me directly at jbiggs@ets.org if you have any follow-up questions.
