### ISSUE TITLE
Scaling constants can differ between analyze() and get_scores()

### ISSUE THREAD

**Issue by sugiyama34** [EducationalTestingService/factor_analyzer#27]
Hi!
I'm a data scientist in Japan and I'm really happy to do factor analysis with rotation in python.
However, one day, I find a problem as follows.

When we try to calculate the factor score from data:
- the data is standardized by using the mean and stdev. of the data itself, not those of data used in `analyze()`;
  - https://github.com/EducationalTestingService/factor_analyzer/blob/d14770044413f5ebbd804d02cf150c7e3c9dc2b3/factor_analyzer/factor_analyzer.py#L1061
- the correlation matrix used is the correlation matrix of the given data, not that of data used in `analyze()`.
  - https://github.com/EducationalTestingService/factor_analyzer/blob/d14770044413f5ebbd804d02cf150c7e3c9dc2b3/factor_analyzer/factor_analyzer.py#L1058

This may cause a problem when the data for `analyze()` and `get_scores()` are not the same.
(I think this situation is not so rare.)

I'm really happy when this problem is fixed.
Thank you :smile:

**Comment by jbiggsets** [comment]
You're absolutely right. We'll fix this in the next release (which should be soon). Thanks very much for catching this issue!

**Comment by jbiggsets** [comment]
This issue has been addressed in the latest release, v0.3.0. Thanks!
