### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by StepfenShawn** [EducationalTestingService/factor_analyzer#30]
I am a beginner,I use Python 3.7 to enter the following code：
import pandas as pd
import numpy as np
from pandas import DataFrame,Series
from factor_analyzer import FactorAnalyzer
 
datafile = 'data.xlsx'
data = pd.read_excel(datafile)
data = data.fillna(0)#用0填充空值
 
fa = FactorAnalyzer()
fa.analyze(data, 5, rotation=None)#固定公共因子个数为5个
print("公因子方差:\n", fa.get_communalities())#公因子方差
print("\n成分矩阵:\n", fa.loadings)#成分矩阵
var = fa.get_factor_variance()#给出贡献率
print("\n解释的总方差（即贡献率）:\n", var)
 
fa_score = fa.get_scores(data)#因子得分
fa_score.head()
 
#将各因子乘上他们的贡献率除以总的贡献率,得到因子得分中间值
a = (fa.get_scores(data)*var.values[1])/var.values[-1][-1]
 
#将各因子得分中间值相加，得到综合得分
a['score'] = a.apply(lambda x: x.sum(), axis=1)

Operation error:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\leave.py", line 11, in <module>
    fa.analyze(data, 5, rotation=None)#固定公共因子个数为5个
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\factor_analyzer\factor_analyzer.py", line 745, in analyze
    method)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\factor_analyzer\factor_analyzer.py", line 580, in fit_factor_analysis
    smc_mtx = self.smc(data).values
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\factor_analyzer\factor_analyzer.py", line 482, in smc
    corr_inv = sp.linalg.inv(corr)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\linalg\basic.py", line 977, in inv
    'getrf|getri' % -info)
ValueError: illegal value in 4-th argument of internal getrf|getri

How to solve？Help me, thank you.

**Comment by jbiggsets** [comment]
Can you share your data set? Feel free to email me at jbiggs@ets.org.

**Comment by StepfenShawn** [comment]
Now I'm going to bed. I'll send you the data tomorrow @jbiggsets

**Comment by stepfencurryxiao** [comment]
I print out the data with Python：
>>> print(data)
                 600000'   浦发银行     ...     Unnamed: 12 Unnamed: 13
0                     日期     开盘     ...             MA5         MA6
1    2017-09-08 00:00:00  12.75     ...          12.797      12.335
2    2017-09-11 00:00:00  13.05     ...          12.806      12.341
3    2017-09-12 00:00:00   12.9     ...          12.819      12.349
4    2017-09-13 00:00:00  12.91     ...          12.828      12.356
5    2017-09-14 00:00:00  12.78     ...          12.832      12.363
6    2017-09-15 00:00:00  12.72     ...          12.836      12.369
7    2017-09-18 00:00:00  12.72     ...           12.84      12.375
8    2017-09-19 00:00:00  12.83     ...          12.843      12.381
9    2017-09-20 00:00:00  12.78     ...          12.845      12.388
10   2017-09-21 00:00:00  12.76     ...          12.847      12.395
11   2017-09-22 00:00:00  12.74     ...          12.851      12.401
12   2017-09-25 00:00:00  12.79     ...          12.857      12.407
13   2017-09-26 00:00:00  12.79     ...          12.862      12.412
14   2017-09-27 00:00:00  12.73     ...          12.866      12.417
15   2017-09-28 00:00:00  12.75     ...          12.869      12.423
16   2017-09-29 00:00:00  12.72     ...          12.874       12.43
17   2017-10-09 00:00:00  13.17     ...          12.882      12.438
18   2017-10-10 00:00:00  12.95     ...          12.887      12.447
19   2017-10-11 00:00:00  12.98     ...          12.891      12.458
20   2017-10-12 00:00:00  12.95     ...          12.887      12.468
21   2017-10-13 00:00:00  12.91     ...          12.876      12.479
22   2017-10-16 00:00:00  12.88     ...          12.864      12.492
23   2017-10-17 00:00:00  12.94     ...          12.855      12.506
24   2017-10-18 00:00:00  12.89     ...          12.844       12.52
25   2017-10-19 00:00:00  12.93     ...          12.836      12.534
26   2017-10-20 00:00:00  12.99     ...          12.829      12.548
27   2017-10-23 00:00:00  12.92     ...          12.815      12.559
28   2017-10-24 00:00:00  12.74     ...          12.804       12.57
29   2017-10-25 00:00:00  12.76     ...          12.796      12.582
..                   ...    ...     ...             ...         ...
233  2018-08-22 00:00:00  10.12     ...           9.872      10.683
234  2018-08-23 00:00:00  10.13     ...           9.868      10.664
235  2018-08-24 00:00:00  10.06     ...           9.865      10.647
236  2018-08-27 00:00:00  10.33     ...           9.861      10.631
237  2018-08-28 00:00:00   10.3     ...           9.855      10.613
238  2018-08-29 00:00:00  10.29     ...           9.851      10.596
239  2018-08-30 00:00:00   10.3     ...           9.846      10.578
240  2018-08-31 00:00:00  10.16     ...           9.843      10.561
241  2018-09-03 00:00:00  10.27     ...           9.842      10.543
242  2018-09-04 00:00:00  10.21     ...           9.843      10.526
243  2018-09-05 00:00:00  10.31     ...            9.84      10.508
244  2018-09-06 00:00:00  10.12     ...           9.841       10.49
245  2018-09-07 00:00:00  10.15     ...           9.842      10.473
246  2018-09-10 00:00:00  10.16     ...           9.842      10.456
247  2018-09-11 00:00:00  10.22     ...           9.845      10.438
248  2018-09-12 00:00:00   9.99     ...           9.849       10.42
249  2018-09-13 00:00:00  10.17     ...           9.859      10.404
250  2018-09-14 00:00:00  10.36     ...           9.869      10.393
251  2018-09-17 00:00:00  10.26     ...            9.88      10.382
252  2018-09-18 00:00:00  10.16     ...           9.895      10.371
253  2018-09-19 00:00:00  10.28     ...           9.911      10.361
254  2018-09-20 00:00:00  10.26     ...           9.925       10.35
255  2018-09-21 00:00:00  10.24     ...           9.942      10.341
256  2018-09-25 00:00:00  10.38     ...           9.961      10.331
257  2018-09-26 00:00:00  10.39     ...           9.981      10.322
258  2018-09-27 00:00:00  10.45     ...          10.002      10.314
259  2018-09-28 00:00:00  10.49     ...          10.026      10.308
260  2018-10-08 00:00:00  10.39     ...          10.041      10.295
261  2018-10-09 00:00:00  10.08     ...          10.052      10.281
262  2018-10-10 00:00:00  10.14     ...          10.063      10.269

[263 rows x 14 columns]
>>>

**Comment by stepfencurryxiao** [comment]
[data.xlsx](https://github.com/EducationalTestingService/factor_analyzer/files/2947904/data.xlsx)

**Comment by StepfenShawn** [comment]
@jbiggsets  Hi,This is my data
[data.xlsx](https://github.com/EducationalTestingService/factor_analyzer/files/2947905/data.xlsx)

**Comment by jbiggsets** [comment]
Hello,

I'm not sure which fields you want to include in your factor analysis. You have two fields in this data set that you have to exclude:

- `日期`, which is a date field.
- `成交笔数`, which is all zeros (and therefore has no variance).

I'm not exactly sure what you are trying to do, but I re-ran your analysis under three scenarios: (1) excluding the two fields above, (2) including only fields that start with `MA`, and (3) excluding the two fields above, as well as any fields that that start with `MA`.

All three of these scenarios worked, without raising any errors.

Here is a copy of the Jupyter notebook I used: [test_issue_30.pdf](https://github.com/EducationalTestingService/factor_analyzer/files/2950211/test_issue_30.pdf)

Let me know if I should close this issue, or if I am misunderstanding something.

Thanks,
Jeremy

**Comment by StepfenShawn** [comment]
Thank you very much! The problem has been solved.
 @jbiggsets
