### ISSUE TITLE
Does this support mixed data? i.e Binary valued vs numerical data

### ISSUE THREAD

**Issue by thusithaC** [EducationalTestingService/factor_analyzer#37]
Hi  jbiggsets, 

Thanks for the package and it has been very helpful for my work. The lack of good statistical packages in Python compared to R is bit of a show stopper. This has indeed been a gem. 

While using the module, I'm curious as to whether it can handle mixed data types as inputs. For example variables from a survey that can be wither binary valued and numerical. 
Thanks!
Thusitha

**Comment by jbiggsets** [comment]
Hi @thusithaC ,

The short answer to your question is that it's probably fine with just a mix of continuous and dichotomous variables. 

Here's the longer answer. By default, the `FactorAnalyzer` class only computes Pearson product-moment correlations. If you have your own correlation matrix, you can pass that directly, and set `use_corr_matrix=True`.

As you probably know, the general rule is as follows:

- With two continuous variables, you want use Pearson product-moment correlation.
- With two categorical variables, you want to use the polychoric correlation.
- With two dichotomous variables, you want to use the tetrachoric correlation.
- With a continuous and categorical (or dichotomous) variable, you want to use the polyserial correlation.
- With a mix of data, you can use a heterogeneous correlation matrix where the pair-wise correlations are calculated using the above rules.

At present, we don't yet offer anything to directly calculate polychoric or polyserial correlations. However, in practice, when you just have a mix of continuous and dichotomous variables, many people will just use Pearson product-moment correlations for everything. So, you're probably fine.

That _isn't_ true when you're dealing with categorical data that has more than two categories. I wouldn't recommend using `FactorAnalyzer` unless you have a way to calculate polychoric or polyserial correlations yourself. This is functionality we'll probably add at some point in the future, but it doesn't exist (at least in this package, or any Python package that I know of) at the moment.

Thanks very much for the question. Let me know if there's any other information I can provide, or if I can close this issue.

**Comment by thusithaC** [comment]
Thanks for the response. 
I have looked at FAMD (https://www.rdocumentation.org/packages/FactoMineR/versions/1.41/topics/FAMD ) implementation in R, and possibly using Rpy for this as well, but unfortunately it doesn't support any type of rotation after the transformation is applied. I guess it might be possible to do the rotation as a secondary step but I didn't get a chance to have a look at in detail. I will also have a look at providing the correlation matrix manually for  factor_analyzer. 

Thanks,
Thusitha

**Comment by jbiggsets** [comment]
Just in case you're not aware, there is a package in R called `polycor` with a `hetcor()`function to generate a heterogeneous correlation matrix using the appropriate pair-wise correlations for mixed data types.

https://www.rdocumentation.org/packages/polycor/versions/0.7-9
