### ISSUE TITLE
KMO value to be NaN

### ISSUE THREAD

**Issue by AgentDS** [EducationalTestingService/factor_analyzer#38]
I try to calculate the KMO value for 4 data sets as:
```
kmo_all1, kmo_total1 = calculate_kmo(df1)
kmo_all2, kmo_total2 = calculate_kmo(df2)
kmo_all3, kmo_total3 = calculate_kmo(df3)
kmo_all4, kmo_total4 = calculate_kmo(df4)
```
where ``df1``,``df2``,``df3``,``df4`` are 4 similar data sets.
And I got ``kmo_total1``, ``kmo_total3``, ``kmo_total4`` higher than 0.85 while ``kmo_total2`` to be ``NaN``. Why? I remember that KMO should be between 0 and 1. By the way that in ``kmo_all2``, all values are ``NaN``. How could it happen?

**Comment by jbiggsets** [comment]
Can you share any of your data sets?

**Comment by jbiggsets** [comment]
Hi @AgentDS, if you have `NaN` values in your data, then you'll get `NaN` results. We're using `numpy.sum()` under the hood.

```
In [1]: import numpy as np                                                                                

In [2]: from factor_analyzer import calculate_kmo                                                         

In [3]: data1 = np.random.randn(100, 3)                                                                   

In [4]: data2 = data1.copy()                                                                              

In [5]: data2[0, 0] = np.nan                                                                              

In [6]: calculate_kmo(data1)                                                                              
Out[6]: (array([0.51823914, 0.51888152, 0.60306026]), 0.5256640646818517)

In [7]: calculate_kmo(data2)                                                                              
Out[7]: (array([nan, nan, nan]), nan)

In [8]: np.sum([5.6, 3.4, np.nan])                                                                        
Out[8]: nan
```

If you don't have `NaN` values in your data, then I'm not sure what's going on, so please let me know if you can provide a sample data set, or at least some additional details about your data.

With regard to your second comment, I'm a little confused. You write, "I got kmo_total1, kmo_total3, kmo_total4 higher than 0.85 . . . I remember that KMO should be between 0 and 1." Is your result outside of the range 0 and 1, or just higher than 0.85?

Let me know if I'm misunderstanding anything, or if this answers your question.

Thanks!

**Comment by jbiggsets** [comment]
Hi @AgentDS, I'm going to close this issue. Please feel free to reopen if you have any additional questions.

**Comment by ricardo-arl** [comment]
Hello, something similar is happening to me. I double checked and my dataset has no NaNs. I think the problem happens when it calculates the partial correlations. Attached you will find the dataset. 

Note: if I change the partial correlation function that comes default with the package to this one, the code works without NaN's. 

https://gist.github.com/fabianp/9396204419c7b638d38f

`def partial_correl(C):
    """
    Returns the sample linear partial correlation coefficients between pairs of variables in C, controlling 
    for the remaining variables in C.
    Parameters
    ----------
    C : array-like, shape (n, p)
        Array with the different variables. Each column of C is taken as a variable
    Returns
    -------
    P : array-like, shape (p, p)
        P[i, j] contains the partial correlation of C[:, i] and C[:, j] controlling
        for the remaining variables in C.
    """

    C = np.asarray(C)
    p = C.shape[1]
    P_corr = np.zeros((p, p), dtype=np.float)
    for i in range(p):
        P_corr[i, i] = 1
        for j in range(i+1, p):
            idx = np.ones(p, dtype=np.bool)
            idx[i] = False
            idx[j] = False
            beta_i = linalg.lstsq(C[:, idx], C[:, j])[0]
            beta_j = linalg.lstsq(C[:, idx], C[:, i])[0]

            res_j = C[:, j] - C[:, idx].dot( beta_i)
            res_i = C[:, i] - C[:, idx].dot(beta_j)

            corr = stats.pearsonr(res_i, res_j)[0]
            P_corr[i, j] = corr
            P_corr[j, i] = corr

    return P_corr`


[DataGithub.zip](https://github.com/EducationalTestingService/factor_analyzer/files/3452069/DataGithub.zip)

**Comment by jbiggsets** [comment]
Hi @ricardo-arl,

I think what's going on here is that the variance-covariance matrix has a determinant that is extremely close to zero, which means it really shouldn't be inverted. However, `numpy` will still calculate the inverse unless the matrix is really, really singular.

```
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: df = pd.read_csv('DataGithub.csv').drop(columns='ID')

In [4]: np.linalg.det(df.cov())
Out[4]: -1.6962495942922608e-48
```

The `partial_correlations()` function in `factor_analyzer` is just a port of the `pcor` function in R. But, unlike R, we do not handle cases where the covariance matrix is ill-conditioned. 

What we can do here is update the function to use the pseudo-inverse when the determinant of the matrix is very close to zero.

```
try:
    if np.linalg.det(x_cov) < np.finfo(np.float32).eps:
        icvx = np.linalg.pinv(x_cov)
    else:
        icvx = np.linalg.inv(x_cov)
except:
    icvx = empty_array
```

This seems to be what's happening in R, so we should probably update this in our package anyway:

https://github.com/cran/ppcor/blob/1631a00104ac08819ef7c757eb380c6de451b5d8/R/ppcor_v1.01.R#L26-L27

When I tested this locally, it solved the problem. One caveat is that you still won't get exactly the same results as the `partial_correl()` function that you posted. But that function isn't taking into account singular variables. You will get the same result you would get with R's `pcor()` function, which is what we're trying to mimic.

**Comment by ricardo-arl** [comment]
Perfect. I think updating it with the pseudo-inverse matrix as pcor does, along with its warning, would be a great way to solve it. 

Thanks!

**Comment by jbiggsets** [comment]
Addressed in `master`
