### ISSUE TITLE
please consider publishing on conda-forge conda channel and supporting python 3.7 (may be via noarch recipe)

### ISSUE THREAD

**Issue by kiwi0fruit** [EducationalTestingService/factor_analyzer#39]

**Comment by spider-z3r0** [comment]
Is this far off? I'd like to use this for confirmatory analysis as I have already used it for EFA and have really liked the module, however, I'm using python 3.7 and I can't seem to upgrade to the latest version.

**Comment by desilinguist** [comment]
There's no plan for conda-forge support as of right now. However, Python versions 3.4-3.7 are now already supported.
