### ISSUE TITLE
Add "Reorder factors after rotation" option to analyze(...) method

### ISSUE THREAD

**Issue by Fireblend** [EducationalTestingService/factor_analyzer#40]
See issue #23 for context:

> when SAS performs the varimax rotation on the factor loading matrix, it is re-ordering the columns according to the amount of variance accounted for by each factor after rotation. The factor_analyzer program is not doing that. It is maintaining the original order of the unrotated factor loading matrix after the rotation is performed.

This would allow the method to replicate SAS' behavior regarding column order in its output.

**Comment by jbiggsets** [comment]
In the latest major release, we actually do reorder the factor columns after rotation, according to the amount of variance accounted for by each factor.

See here:

https://github.com/EducationalTestingService/factor_analyzer/blob/553656edccc02aec3ea0dbd96c23ab87827707fe/factor_analyzer/factor_analyzer.py#L654-L656

But please let me know if something isn't working correctly, or if you have any other suggestions.

**Comment by jbiggsets** [comment]
I'm going to close this issue. Please feel free to reopen if you have any other questions.
