### ISSUE TITLE
ddof biased

### ISSUE THREAD

**Issue by blessu** [EducationalTestingService/factor_analyzer#42]
First, thanks a lot for this module, much more convenient than the function in sklearn.

The setting of `cov` calculation (and thus `corr`) is biased, because the parameter is set `ddof=0`.

https://github.com/EducationalTestingService/factor_analyzer/blob/553656edccc02aec3ea0dbd96c23ab87827707fe/factor_analyzer/utils.py#L28

Any mathematical reason?

**Comment by jbiggsets** [comment]
This is a good question.

We only use the `cov()`  function in CFA, which is still very much a work-in-progress. In general,  want our output to imitate R's `lavaan` package, and by default `lavaan` is rescaling the sample covariance to the population. 

However, you're right that if anyone wants to use this function outside of `factor_analyzer`, this probably isn't what they want. I'll make `ddof`  an optional parameter. Let me know if you have other suggestions/concerns, or if I can close this issue.

**Comment by blessu** [comment]
Thanks, it may also affect the `calculate_kmo` function.

**Comment by jbiggsets** [comment]
Ah, you're right. Thanks for submitting the issue, I'll update this soon!

**Comment by jbiggsets** [comment]
Addressed this in the `master` branch.
