### ISSUE TITLE
Bug when ussing oblimin rotation

### ISSUE THREAD

**Issue by GSnuiv** [EducationalTestingService/factor_analyzer#46]
Hi! 

First of all thanks for the aesome package, I've found it very usefull, but there is something I cannot do, use the gamma parameter for oblimin rotation.

When I execute    ```FactorAnalyzer(n_factors=x[0], rotation=x[1],method=x[2], rotation_kwargs={'gamma':0.5},  use_smc=True )```  the error launched is the following:

 ```ValueError: Input must be 1- or 2-d.```

It's appear to come from here

https://github.com/EducationalTestingService/factor_analyzer/blob/553656edccc02aec3ea0dbd96c23ab87827707fe/factor_analyzer/rotator.py#L196

If I'm completly honest I don't know how to fix it but I think what is needed is ti implement the X as in quartimin minuns 

<a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;-&space;\gamma&space;\frac{1}{k}&space;\sum_v&space;p_i^2&space;\sum_v&space;p_j^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\gamma&space;\frac{1}{k}&space;\sum_v&space;p_i^2&space;\sum_v&space;p_j^2" title="- \gamma \frac{1}{k} \sum_v p_i^2 \sum_v p_j^2" /></a> 

[<a href="https://books.google.es/books?id=mCwlDwAAQBAJ&pg=PA195&dq=oblimin&hl=es&sa=X&ved=0ahUKEwjqsair9sjkAhUxAWMBHQbNBzQQ6AEITDAE#v=onepage&q=quartimin&f=false" target="_blank"> Math from here </a> ]

**Comment by jbiggsets** [comment]
Definitely a bug. Thanks for catching this!

That should be `np.diag(np.full(1, p))`. I'll address this in the current PR I'm working on. We're planning on a new release in the next couple weeks, so this is very timely.

**Comment by jbiggsets** [comment]
I've addressed this in the `master` branch. Will be incorporated in the next release.
