### ISSUE TITLE
Structural Equation Modeling

### ISSUE THREAD

**Issue by dmnapolitano** [EducationalTestingService/factor_analyzer#49]
Port of the SEM code from R's `lavaan` package 👍

**Comment by dmnapolitano** [comment]
It seems as though I can't assign myself to this issue lol 🤔

**Comment by dmnapolitano** [comment]
Although: https://arxiv.org/abs/1905.09376

@jbiggsets 🤔

**Comment by jbiggsets** [comment]
Closing this issue. People can use the new `semopy` 2.0 package for SEM.

https://pypi.org/project/semopy/
