### ISSUE TITLE
Factor Loading - possible error

### ISSUE THREAD

**Issue by eyalshafran** [EducationalTestingService/factor_analyzer#5]
In line 194,195 the eigenvalues are sorted but the eigenvectors are not:

        values = sorted(values, reverse=True)[:n_factors]
        vectors = vectors[:, :n_factors]

The factor loadings are then calculated in line 200:

            loadings = np.dot(vectors,
                              np.diag(np.sqrt(values)))

I think that the vectors need to be sorted by the same order as the values, otherwise, you are not multiplying the correct eigenvalues with the eigenvectors.

**Comment by jbiggsets** [comment]
Thanks for pointing this out, @eyalshafran. I will take a look. :)

**Comment by jbiggsets** [comment]
Thanks again for pointing this out. We have made some fixes to `master`, which will be included in the next release.
