### ISSUE TITLE
Add weights attribute

### ISSUE THREAD

**Issue by Xylambda** [EducationalTestingService/factor_analyzer#53]
Hi,

I would like to suggest a new attribute to the `factor_analyzer.py` module. Some applications require to access the weights (B) used to calculate F = Z · B in the `transform` method. 

As an example, I leave a paper with such use (`Table 9: Component score coefficient matrix`):
https://www.researchgate.net/publication/227440018_Constructing_an_alternative_dollar_index_to_gauge_the_movements_in_currency_markets

Would it be possible to add a new attribute to access them? Maybe something like:
```python
def __init__(self, ...):
    # ...
    self.weights_ = None


def transform(self, X):
    # ...
    try:
        self.weights_ = np.linalg.solve(self.corr_, structure)
    except Exception as error:
        warnings.warn('Unable to calculate the factor score weights; '
                            'factor loadings used instead: {}'.format(error))
        self.weights_ = self.loadings_
    # ...

# # # #
fa = FactorAnalyzer(...)
fa.fit(my_data)
fa.transform(my_data)
my_weights = fa.weights_
```
Thanks in advance

**Comment by desilinguist** [comment]
Hi @Xylambda, thanks for the suggestion! Any change you’d have the bandwidth to submit a pull request? It’d be most appreciated!

**Comment by Xylambda** [comment]
Hi @desilinguist 
No problem.
You can find it [here](https://github.com/EducationalTestingService/factor_analyzer/pull/55).
