### ISSUE TITLE
issue about bartlett.

### ISSUE THREAD

**Issue by cbtq** [EducationalTestingService/factor_analyzer#57]
def calculate_bartlett_sphericity(x):
    """
    Test the hypothesis that the correlation matrix
    is equal to the identity matrix.identity

    H0: The matrix of population correlations is equal to I.
    H1: The matrix of population correlations is not equal to I.

    The formula for Bartlett's Sphericity test is:

    .. math:: -1 * (n - 1 - ((2p + 5) / 6)) * ln(det(R))

    Where R det(R) is the determinant of the correlation matrix,
    and p is the number of variables.

    Parameters
    ----------
    x : array-like
        The array from which to calculate sphericity.

    Returns
    -------
    statistic : float
        The chi-square value.
    p_value : float
        The associated p-value for the test.
    """
    n, p = x.shape
    x_corr = corr(x)

    corr_det = np.linalg.det(x_corr)
    statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)
    degrees_of_freedom = p * (p - 1) / 2
    p_value = chi2.sf(statistic, degrees_of_freedom)
    return statistic, p_value

英文不好，这里的p_value = chi2.pdf(statistic, degrees_of_freedom)改为sf，另外感谢原作者，已星星！
English poor, code"p_value = chi2.pdf(statistic, degrees_of_freedom)" change "sf" , thanks and star.

**Comment by jbiggsets** [comment]
Sorry, I totally understand. This should be 1 - `cdf`, not `pdf` Addressing this in #66.

**Comment by jbiggsets** [comment]
This is resolved with PR #66. Will be incorporated into the next release.
