### ISSUE TITLE
When doing EFA, is there a  way to pass random_state to externalized_svd

### ISSUE THREAD

**Issue by pinpointcoder** [EducationalTestingService/factor_analyzer#62]
Currently different runs of EFA produces different results, It will be great if we can control it by passing the `random_state` to `externalized_svd`.

Let me know if this requests makes sense, I can raise a pull request.

Thanks for the library

Cheers

**Comment by desilinguist** [comment]
Hi @pinpointcoder please feel free to submit a PR. This sounds quite useful.

**Comment by jbiggsets** [comment]
I'll work on this.
