### ISSUE TITLE
Add Geomin rotation

### ISSUE THREAD

**Issue by zeromh** [EducationalTestingService/factor_analyzer#63]
I'm doing work in python for which I'd like to use geomin rotation. I see that geomin isn't implemented in `factor_analyzer`. It looks straightforward to implement and I was considering doing so.

I think I'd have to create a `_geomin_obj` function in `rotator.py` that gives the gradient and criterion for geomin. The equations for this are in "GRADIENT PROJECTION ALGORITHMS AND SOFTWARE FOR ARBITRARY ROTATION CRITERIA IN FACTOR ANALYSIS", which R's GPArotation package references, so writing that code should be easy.  Given a geomin objective, I believe `Rotator` should be able to use the generic `_oblique` rotation function?

The `Rotator` class would also need an `epsilon` parameter.

And thoughts on this and can you confirm my understanding here?

**Comment by desilinguist** [comment]
Hi @zeromh! That sounds pretty reasonable to me. Thank you so much for your suggestion and I look forward to your PR!

**Comment by zeromh** [comment]
What's expected in terms of unit tests? From what I can gather, there is a lot of manual work to set up an R env, create R loadings, and write a lot of unit tests that do the same thing on different data sets (this could have been parametrized). 

Also what is used to run tests? I don't see `unittest` or `pytest`...

**Comment by desilinguist** [comment]
Take a look at the tests folder for unit tests. We use nose to run the tests and Travis CI is used to automatically run the tests for every branch.

________________________________

**Comment by zeromh** [comment]
Ah, I'm not familiar with nose but it looks straightforward enough. I'll plan on running tests with that.

My question is still what tests exactly do you require for a new Rotator method, and what's the process for creating the necessary components (e.g. geomin-rotated loadings from R, if that's what you're testing against)?

**Comment by jbiggsets** [comment]
Hi @zeromh: In general, the process has been to run test data through R (specifying a few different factor numbers). You can find test data [here](https://github.com/EducationalTestingService/factor_analyzer/tree/master/tests/data) or feel free to add your own.

Once you've run the data through R, generate CSVs for the loadings, communalities, etc. Then write your unit tests to make sure that the `factor_analyzer` function matches the R output. 

If you need help with this or if that doesn't make sense, just let me know.

**Comment by jbiggsets** [comment]
Added a WIP PR to address this issue.

**Comment by zeromh** [comment]
Right, so different rotator methods use different test data sets. For example, `oblimin` uses test sets 2, 4, 7, and 7gamma. Which tests do you expect in order to approve a PR? 

Also, I was planning on adding geomin only for oblique rotation. The paper on these methods notes that geomin may not be very useful for orthogonal (although R does implement it). Thoughts?

**Comment by jbiggsets** [comment]
@zeromh, yup, that's correct with regard to the test data.

I submitted a PR for both the oblique and orthogonal rotations and added you as a reviewer. It didn't require a lot of additional code to implement for both, so I figured there was no reason not to. 

Please take a look when you get a chance and let me know if this isn't what you had in mind, or feel free to make changes/additions! I've added a few tests, just using the `test02` data.

**Comment by desilinguist** [comment]
Addressed by #64.
