### ISSUE TITLE
Rename package to `factorum`

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/factor_analyzer#65]
For the next release, let's rename the package to `factorum`.

**Comment by desilinguist** [comment]
We'll have to figure out what to do about the existing packages. Do we just abandon that one or do something more specific? This might be a good reference: https://www.dampfkraft.com/code/how-to-deprecate-a-pypi-package.html

Redirect seems like a good option? I wonder if anaconda.org allows something like that.

**Comment by jbiggsets** [comment]
Cool. I will take a look!

**Comment by desilinguist** [comment]
This is no longer on the roadmap.
