### ISSUE TITLE
calculate_bartlett_sphericity error

### ISSUE THREAD

**Issue by claudiomartelli** [EducationalTestingService/factor_analyzer#69]
The function calculate_bartlett_sphericity(x) return the following error:

/usr/local/lib/python3.6/dist-packages/factor_analyzer/factor_analyzer.py:118: RuntimeWarning: invalid value encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)

I verified that: 
with my data: 

np.linalg.det(x_corr)= -3.545142402311294e-53

so the problem is the log on a negative number.
Is there a problem with the test's formula?

**Comment by jbiggsets** [comment]
Hmm. I don't think there's anything wrong with the formula.

Can you share the `x_corr` matrix? I don't think the determinant of a correlation matrix should be negative, if the matrix is actually positive semi-definite. But let me know if you think I'm missing anything.

(Alternatively, if you can't share the matrix, can you check to make sure all the eigenvalues of `x_corr` are positive?)

**Comment by desilinguist** [comment]
@claudiomartelli I am going to close this issue. If you want to continue the conversation, please reopen it.
