### ISSUE TITLE
Add RMSEA, Chi2, CFI and Tucker-Lewis index as quality indices

### ISSUE THREAD

**Issue by JohannesWiesner** [EducationalTestingService/factor_analyzer#70]
I am referring to this [stackoverflow post](https://stackoverflow.com/q/58719228/8792159) where the user **KevOMalley743** had the idea to add RMSEA, Chi2, CFI and Tucker-Lewis index as quality indices for the `factor_analyzer.confirmatory_factor_analyzer.ConfirmatoryFactorAnalyzer` class. Is there a plan to include this indices?

**Comment by desilinguist** [comment]
Hi @JohannesWiesner there aren't any immediate plans to do this but we will welcome any PRs 🙏!

**Comment by JohannesWiesner** [comment]
For my current research project, I might use `factor_analyzer.confirmatory_factor_analyzer.ConfirmatoryFactorAnalyzer`. If I should have to calculate those indices anyway, I will share the code with you (though I am not sure if I have enough time to dig deep into your code and send a complete PR that respects your object-oriented structure).

**Comment by jbiggsets** [comment]
@JohannesWiesner, I don't think we're planning to include these metrics any time soon, but if you're interested, the `semopy` package has a much more robust API for confirmatory factor analysis and includes all of the statistics you mentioned (see [here](https://gitlab.com/georgy.m/semopy/-/blob/master/semopy/stats.py)).

[Here](https://pypi.org/project/semopy/) is the PyPI page, and [here](https://semopy.com/tutorial.html) is a tutorial. Please let me know if this is helpful and if I can close this issue for now.

**Comment by JohannesWiesner** [comment]
@jbiggsets, yes I've also discovered the `semopy` package in the meantime. Thanks for linking to it, you can close this issue.
