### ISSUE TITLE
correct way to calculate correlations between factors

### ISSUE THREAD

**Issue by sergemelnikov86** [EducationalTestingService/factor_analyzer#85]
Could you please look this question, where is my mistalke there?
https://stackoverflow.com/questions/67856186/correct-way-to-calculate-correlations-between-factors

**Comment by jbiggsets** [comment]
Hello, I responded to your question on StackOverflow. Please let me know if
you have any additional questions.

Thanks,
Jeremy

**Comment by desilinguist** [comment]
Fantastic answer @jbiggsets !

**Comment by sergemelnikov86** [comment]
@jbiggsets thanks for an answer! will try to understand how works this check method.. can you please tell what is mistake in my method "get_correlations_between_factors" (by factor scores) and why it gave correct (almost identity) matrix for sklearn package FA?
