### ISSUE TITLE
Very strange result of varimax FA

### ISSUE THREAD

**Issue by sergemelnikov86** [EducationalTestingService/factor_analyzer#87]
I'm making web version of Kelly's rep test, where we have table of estimations of people by user generated features and by FA we extract factors from this table by fa.transform(df); resulting table always has typically for normal distribution values (from about -3 to 3). But for one case I recieved very strange result (it's on attached image). I've checked - without rotation we have typically table, it seems there is some error (or maybe not all tables are suitable for varimax rotation? but I've also checked with sklearn FA package, it gave normal result with varimax). Can you please check this case? Of course, I can send table in any format
[Image](https://drive.google.com/file/d/1BCPaeKDFYWTAhcNiwOkN1yJ2236uPUBB/view?usp=sharing)

**Comment by sergemelnikov86** [comment]
calculate_kmo(df) for this table gives kmo_total=0.162, can this explain such strange result? (but why without rotation and with varimax by sklearn we have normal result table)?

**Comment by sergemelnikov86** [comment]
if this is a silly question, can you please at least briefly answer why it is? I'm not an expert at all, but out of about 20 cases this is really the only one with such strange values..

**Comment by desilinguist** [comment]
@jbiggsets any ideas here?

**Comment by sergemelnikov86** [comment]
here is the table of raw values (if any other format is convinient I can send as well of course) https://docs.google.com/spreadsheets/d/17IKteczU-KX6GB-bsNRh8WKXLuersVcCZV1mFOvLymA/edit?usp=sharing

**Comment by jbiggsets** [comment]
Hi @sergemelnikov86, I took a quick look. I'm not entirely sure about the factors being normally distributed without rotation, but the KMO score for your dataset is extremely low, which means it really isn't appropriate for factor analysis. There are some very high correlations (and partial correlations) in your data, including one correlation that's greater than 0.9. 

When I ran the dataset through R's `psych::fa()` function, I also got a series of warnings:

```
library(psych)

df <- read.csv('repgrid65.csv')
df <- subset(df, select = -c(X))
res <- fa(df, rotate = 'varimax', fm = 'minres', nfactors = 3)

Warning message in cor.smooth(R):
“Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(R):
“Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(R):
“Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(r):
“Matrix was not positive definite, smoothing was done”Warning message in fa.stats(r = r, f = f, phi = phi, n.obs = n.obs, np.obs = np.obs, :
“The estimated weights for the factor scores are probably incorrect.  Try a different factor extraction method.”Warning message in sqrt(1/diag(V)):
“NaNs produced”Warning message in cov2cor(t(w) %*% r %*% w):
“diag(.) had 0 or NA entries; non-finite result is doubtful”
```

Given that the weights could not be correctly calculated, the `psych` library actually doesn't even provide scores (with or without rotation):

```
res$scores 
NULL
```

I'd like to think about whether it makes sense of `factor_analyzer` to do something similar to `fa()` in cases like this, but I don't think this is a bug in `factor_analyzer`. It's definitely an issue with your data. 

Let me know if I'm missing anything, or if I can close this issue.

**Comment by sergemelnikov86** [comment]
> Hi @sergemelnikov86, I took a quick look. I'm not entirely sure about the factors being normally distributed without rotation, but the KMO score for your dataset is extremely low, which means it really isn't appropriate for factor analysis. There are some very high correlations (and partial correlations) in your data, including one correlation that's greater than 0.9.
> 
> When I ran the dataset through R's `psych::fa()` function, I also got a series of warnings:
> 
> ```
> library(psych)
> 
> df <- read.csv('repgrid65.csv')
> df <- subset(df, select = -c(X))
> res <- fa(df, rotate = 'varimax', fm = 'minres', nfactors = 3)
> 
> Warning message in cor.smooth(R):
> “Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(R):
> “Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(R):
> “Matrix was not positive definite, smoothing was done”Warning message in cor.smooth(r):
> “Matrix was not positive definite, smoothing was done”Warning message in fa.stats(r = r, f = f, phi = phi, n.obs = n.obs, np.obs = np.obs, :
> “The estimated weights for the factor scores are probably incorrect.  Try a different factor extraction method.”Warning message in sqrt(1/diag(V)):
> “NaNs produced”Warning message in cov2cor(t(w) %*% r %*% w):
> “diag(.) had 0 or NA entries; non-finite result is doubtful”
> ```
> 
> Given that the weights could not be correctly calculated, the `psych` library actually doesn't even provide scores (with or without rotation):
> 
> ```
> res$scores 
> NULL
> ```
> 
> I'd like to think about whether it makes sense of `factor_analyzer` to do something similar to `fa()` in cases like this, but I don't think this is a bug in `factor_analyzer`. It's definitely an issue with your data.
> 
> Let me know if I'm missing anything, or if I can close this issue.

Hi @jbiggsets , thanks for an answer! Unfortunately my math knowledge is still too low to understand that problem, but do you know why again sklearn.factor_analysis gives appropriate result for this data with varimax? What optimisation can be there for such data? Your facror_analyzer has much prettier and rich interface and I want to use only it but now only way I see is to run factor_analyzer, check values for extremely big like here and if they are change method to sklearn.factor_analysis (and instead kmo is too small psychologicaly 3 factors that turned out here really have sense)
And, sorry again, maybe mathematically it's silly question (and I still didn't learn mechanics of FA), but why correlated columns disturb FA - why can't they be initially united to one factor?

**Comment by jbiggsets** [comment]
Can you explain what you mean when you say that the scores from `sklearn`'s `fa.transform()` method are normally distributed while the `FactorAnalyzer` score are not?

Here are the results that I get:

<img width="936" alt="Screen Shot 2021-10-06 at 8 58 22 PM" src="https://user-images.githubusercontent.com/30508716/136303879-fa002897-f71e-4f2e-bbbb-d7015584d31c.png">

**Comment by sergemelnikov86** [comment]
@jbiggsets  Oh, I'm sorry -- strange result comes when one column is deleted _(I tried to delete columns that are badly explained by FA - have little explained variance score - and perform FA without them and then show factors plus this columns)_, forgot to make this, now updated table:
https://docs.google.com/spreadsheets/d/17IKteczU-KX6GB-bsNRh8WKXLuersVcCZV1mFOvLymA/edit#gid=0
Check again please
Normal I meant standart normal (with mean 0 and dispersion 1, for all other results I saw maximum module of factor scores wasn't greater than 3, don't know if it is correct to talk about standart normal distribution, just meant all values are not greater than 3 by module and most often there are in interval approximately (-1.5, 1.5))
Here are the factor scores for sklearn.FactorAnalysis and for FactorAnalyzer (also checked FactorAnalyzer without rotation, modules are still same big, so my first message about it was wrong):

[[ 0.81385971  1.05852143  0.08911612]
 [ 1.30572232  0.04800113  0.20196504]
 [ 0.21484406  0.08218549  1.05525899]
 [-0.12957322 -1.7385097   0.17377177]
 [ 0.29963363  1.18228332  0.57451435]
 [ 1.67057673 -0.96039432 -0.52884211]
 [-1.40449712 -0.78883152 -1.14686695]
 [-1.1835083  -0.29515398 -1.27794889]
 [-0.78570261  0.09568664 -1.83128036]
 [ 0.567205    2.04436677 -1.29544197]
 [ 0.79733565  0.27977961 -0.0684163 ]
 [-1.27247079 -0.31509567  0.73546925]
 [-0.78433329  0.7211403   0.3310474 ]
 [-1.3499985   0.72456827  1.92606996]
 [ 1.14360703 -1.53485955  0.36921986]
 [ 0.09729969 -0.60368823  0.69236383]]

[[  1.99276256  -4.58285485   9.3384365 ]
 [ -1.07779043   0.03895484   0.05530536]
 [ -0.39432878   2.41126195  -2.77996459]
 [ -0.31843563  -1.40650308  -0.52910977]
 [  2.23935474  -3.56107662   8.70132039]
 [ -5.89287321   7.11918494 -11.28812633]
 [  2.25231227  -4.2956614    3.57650838]
 [ -3.82030903   7.59955644 -14.58151524]
 [  2.46565971  -3.93027925   4.92489014]
 [  0.62650407   1.4002316    0.61176098]
 [ -5.56301584   8.51743212 -14.57927398]
 [  4.67909693  -6.19516319   9.24251933]
 [  1.1812174   -0.76292308   2.35445472]
 [  0.44472457   3.46677006  -3.47397181]
 [  6.47900371 -15.63098864  24.48783262]
 [ -5.29388304   9.81205816 -16.06106671]]

![2](https://user-images.githubusercontent.com/85429174/136338647-acfc77c3-1dd2-4434-93ee-4aa31e25d250.png)

**Comment by jbiggsets** [comment]
Got it. I see what's going on now.

There are different ways of calculating factor scores. `FactorAnalyzer` uses regression, which is the default in R's `psych` package. When you calculate the scores in R using your dataset with the default `scores="regression"` option, you get the following:

<img width="332" alt="Screen Shot 2021-10-07 at 2 23 40 PM" src="https://user-images.githubusercontent.com/30508716/136441379-cb10e016-96e5-45b3-ae3f-6d7d130ef1e1.png">

Here's the distribution:

<img width="591" alt="Screen Shot 2021-10-07 at 2 25 11 PM" src="https://user-images.githubusercontent.com/30508716/136441572-fd76a19f-8bb4-4d43-a1f4-9b8109d37194.png">

With the regression method, scores have a mean of zero and a variance equal to the squared multiple correlation between the estimated factor scores and the true factor values. The partial correlations in your data are extremely high (too high for factor analysis, as indicated by the KMO score), which I think it causing some issues here.
<img width="863" alt="Screen Shot 2021-10-07 at 1 50 56 PM" src="https://user-images.githubusercontent.com/30508716/136442459-917bca3c-6e0a-404e-846c-991da116efe4.png">

There are other ways of calculating factor scores, though. It seems like `scikit-learn` is using Bartlett scores (or something similar?), which are calculated by minimizing the sum of squares of the unique factors over the range of the variables.

We don't have Bartlett scores implemented in `FactorAnalyzer` (yet), but `psych` now does. The scores you get from that method in R are very similar to what you got from `scikit-learn`.

<img width="322" alt="Screen Shot 2021-10-07 at 2 34 19 PM" src="https://user-images.githubusercontent.com/30508716/136442956-8bf765ad-9f18-4863-bd1c-cadb3bfe6455.png">

Let me know if you have any other questions, and thanks for the clarification. Otherwise, I'm going to close this issue. I will likely open a separate issue to implement Bartlett scores at some point in the future, since I do think that would be worthwhile.

One final note: We don't generally try to match `scikit-learn`'s output, since they use a method of factor analysis that often does not align with most other implementations.

**Comment by sergemelnikov86** [comment]
Ok, thanks for the explanation!
